version: "3.7"
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/app
      - ./.config/site.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NGINX_HOST=php-docker.local
      - NGINX_PORT=80
    links:
      - php
  php:
    image: php:7.4-fpm
    ports:
      - 9000:9000
    working_dir: /app
    volumes:
      - ./:/app
volumes:
  pg-data:
