version: "3.7"
services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./images/nginx/site.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NGINX_PORT=80
    links:
      - php
  php:
    image: php-xdebug
    build:
      context: images/php/
    ports:
      - 9000:9000
    working_dir: /app
    volumes:
      - ./:/app
      - ./images/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini