version: "3.3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "7415:80"
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NGINX_PORT=80
    links:
      - php
  php:
    image: protvs/php-test-app:1.0
    ports:
      - 9000:9000
    working_dir: /app
